apiVersion: node.harvesterhci.io/v1beta1
kind: CloudInit
metadata:
  name: multipath-ibm-v7000
  namespace: harvester-system
spec:
  matchSelector: {}
  filename: 99_multipath_ibm_v7000.yaml
  contents: |
    stages:
      initramfs:
        - name: "Configure multipath for PowerMax"
          files:
            - path: /etc/multipath.conf
              permissions: 0644
              owner: 0
              group: 0
              content: |
                defaults {
                    user_friendly_names "yes"
                }
                blacklist {
                    wwid 3600062b208887fc02b7cfbb331f5ce82
                    wwid 3600062b21152a7002b7cfab1b2392d83
                    wwid 3600062b21152a7002b73f40cdad91dc0
                    devnode "^sda"
                }
                devices {
                    device {
                            vendor "IBM"
                            product "^2145"
                            path_grouping_policy "group_by_prio"
                            path_selector "round-robin 0"
                            prio "alua"
                            path_checker "tur"
                            failback "immediate"
                            no_path_retry "5"
                            rr_weight "uniform"
                            rr_min_io_rq 1  
                    }
                }
      boot:
        - name: "Enable and start multipathd"
          systemctl:
            enable:
              - multipathd
            start:
              - multipathd
